services:
  api:
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - "db"
    environment:
      NODE_ENV: "production"
      PORT: 3000
      ONLY_LISTEN_LOCAL: "false"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: place
      MONGO_INITDB_ROOT_PASSWORD: password    # Don't use this password in production
    volumes:
      - mongo-volume:/data/db
    expose:
      - "27017"
volumes:
  mongo-volume: